import PagePadding from "../../components/server/layout/PagePadding";
import Navbar from "../../components/server/navigation-bar/Navbar";
import FooterSection from "../../components/server/section/FooterSection";
import SideLinks from "../../components/server/sidelinks/SideLinks";
import "./globals.css";
import { Inter, Rubik } from "next/font/google";

const rubik = Rubik({ subsets: ["latin"], display: "swap" });

export const metadata = {
  title: "Taha Sokmen - Personal Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <Navbar></Navbar>
        <SideLinks></SideLinks>
        {children}
        <FooterSection></FooterSection>
      </body>
    </html>
  );
}
